CREATE DATABASE libreria;

USE libreria;

CREATE TABLE libro(
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(100) NOT NULL,
  autor VARCHAR(100) NOT NULL,
  editorial VARCHAR(100) NOT NULL,
  codigo VARCHAR(10) NOT NULL,
  ejemplares INT(11) NOT NULL
);

CREATE TABLE estudiante(
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  codigo VARCHAR(10) NOT NULL,
  INE VARCHAR(30) NOT NULL,
  celular VARCHAR(15) NOT NULL
);

CREATE TABLE profesor(
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  codigo VARCHAR(10) NOT NULL,
  INE VARCHAR(30) NOT NULL,
  celular VARCHAR(15) NOT NULL
);
